name: Unit Cases

on: 
push:
    branches:
      - "master"

jobs:
    tests: 
      runs on: ubuntu_latest
      
      srategy:
      matrix:
      node_version: [16.x]
      
steps: 
- uses: actions/checkout@v2
- name: Use Node.js ${{ matrix.node-version }}
  uses: actions/checkout@v1
  with:
    node version: ${{ matrix.node-version }}
- name: npms install
run: npm ci
- name: tests
run: npm test
      
   
