name: React CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          cd app-react
          npm install
          npm run build --if-present
